name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run test

      - name: Generate version number
        uses: semantic-release/exec
        with:
          args: |
            npx semantic-release --dry-run

      - name: Build and tag Docker image
        uses: docker/build-push-action
        with:
          context: .
          push: true
          tags: |
            ghcr.io/nathanszig/vue-images:${{ env.DOCKER_TAG }}
          build-args: |
            VERSION=${{ env.DOCKER_TAG }}

      - name: Push version number to GitHub
        uses: semantic-release/github
        with:
          github_token: ${{ secrets.TOKEN }}
