name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run test:unit

      - run: npm run build
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        run: npx semantic-release@17 --rc-path .releaserc
      - name: Create docker image
        run: |
          docker build -t vue-images .
          docker tag vue-images ghcr.io/nathanszig/vue-images:${{ env.RELEASE_VERSION }}
          docker push ghcr.io/nathanszig/vue-images:${{ env.RELEASE_VERSION }}
