name: CI
permissions:
  contents: write

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run test:unit
      
      - name: Get Release Version
        id: get_version
        run: echo "RELEASE_VERSION=$(npx semantic-release@17 --rc-path .releaserc --dry-run | grep -oP '(?<=\@).*(?=\s)')" echo $RELEASE_VERSION
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}

      # Use the release version and release the package

      - name: Release package
        uses: cycjimmy/semantic-release-action@v2
        with:
          semantic_version: ${{ steps.get_version.outputs.RELEASE_VERSION }}
          extra_plugins: |
            @semantic-release/exec
          exec: |
            npm publish --access public

      
      
